
#testdata options: test1, test2

testedDataSet: test1

testData:
  test1:
    envName: test1
    appUrl: http://automationpractice.com/index.php?id_category=7&controller=category
    blousesCategoryTitle: Blouses - My Store


  test2:
    envName: test2
    appUrl: http://automationpractice.com/index.php
    blousesCategoryTitle: Blouses - My Store


---